# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieHouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieHouse
pod 'Alamofire'
pod 'AlamofireImage'

  target 'MovieHouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieHouseUITests' do
    # Pods for testing
  end

end
